site_name: toolops
site_description: Documentation for toolops
repo_name: jonwraymond/toolops
repo_url: https://github.com/jonwraymond/toolops
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Design Notes: design-notes.md
  - User Journey: user-journey.md
theme:
  name: material
